# Generated by Django 6.0.2 on 2026-02-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasvupaikka', models.CharField(blank=True, default='', help_text='Esim. parvekelaatikko, kasvihuone, palsta', max_length=100, verbose_name='Kasvupaikka')),
                ('tila', models.CharField(choices=[('odottaa', '🌑 Odottaa kylvöä'), ('kylvetty', '🌱 Kylvetty'), ('itanyt', '🌿 Itänyt'), ('kasvaa', '💚 Kasvaa hyvin'), ('sadonkorjuu', '🍅 Sadonkorjuussa'), ('paattynyt', '✅ Päättynyt')], default='odottaa', max_length=20, verbose_name='Tila')),
                ('kylvopaiva', models.DateField(blank=True, null=True, verbose_name='Kylvöpäivä')),
                ('muistiinpanot', models.TextField(blank=True, default='', verbose_name='Muistiinpanot')),
                ('lisatty', models.DateTimeField(auto_now_add=True, verbose_name='Lisätty')),
            ],
            options={
                'verbose_name': 'Viljelymerkintä',
                'verbose_name_plural': 'Viljelymerkinnät',
                'ordering': ['-lisatty'],
            },
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nelson_garden_id', models.CharField(blank=True, default='', max_length=20, verbose_name='Nelson Garden ID')),
                ('nimi', models.CharField(max_length=100, verbose_name='Nimi')),
                ('lajike', models.CharField(blank=True, default='', max_length=100, verbose_name='Lajike')),
                ('kategoria', models.CharField(max_length=50, verbose_name='Kategoria')),
                ('kuvaus', models.TextField(blank=True, default='', verbose_name='Kuvaus')),
                ('kasvatusohje', models.TextField(blank=True, default='', verbose_name='Kasvatusohje')),
                ('kylvo_alku_kk', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Kylvö alkaa (kk)')),
                ('kylvo_loppu_kk', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Kylvö päättyy (kk)')),
                ('sato_alku_kk', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Sato alkaa (kk)')),
                ('sato_loppu_kk', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Sato päättyy (kk)')),
                ('itamisaika_min_pv', models.IntegerField(default=7, verbose_name='Itämisaika min (pv)')),
                ('itamisaika_max_pv', models.IntegerField(default=14, verbose_name='Itämisaika max (pv)')),
                ('korkeus_cm', models.IntegerField(blank=True, null=True, verbose_name='Korkeus (cm)')),
                ('kasvupaikka', models.CharField(choices=[('aurinko', 'Aurinko'), ('puolivarjo', 'Puolivarjo'), ('varjo', 'Varjo')], default='aurinko', max_length=20, verbose_name='Kasvupaikka')),
                ('siemenia_pakkauksessa', models.IntegerField(blank=True, null=True, verbose_name='Siemeniä pakkauksessa')),
                ('nelson_garden_url', models.URLField(blank=True, default='', verbose_name='Nelson Garden URL')),
            ],
            options={
                'verbose_name': 'Kasvilaji',
                'verbose_name_plural': 'Kasvilajit',
                'ordering': ['kategoria', 'nimi'],
            },
        ),
        migrations.CreateModel(
            name='GardenNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paivamaara', models.DateField(verbose_name='Päivämäärä')),
                ('havainto', models.TextField(verbose_name='Havainto')),
                ('kasvi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='havainnot', to='garden.mygarden', verbose_name='Viljelymerkintä')),
            ],
            options={
                'verbose_name': 'Havainto',
                'verbose_name_plural': 'Havainnot',
                'ordering': ['-paivamaara'],
            },
        ),
        migrations.AddField(
            model_name='mygarden',
            name='kasvilaji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viljelyt', to='garden.plantspecies', verbose_name='Kasvilaji'),
        ),
    ]
