# Generated by Django 6.0.2 on 2026-02-28 09:35

from django.db import migrations


def migrate_categories(apps, schema_editor):
    PlantSpecies = apps.get_model('garden', 'PlantSpecies')
    Category = apps.get_model('garden', 'Category')

    # Mapping of existing categories to names with emojis
    category_map = {
        'Chili': '🌶️ Chili',
        'Juurekset': '🥕 Juurekset',
        'Marjat': '🍓 Marjat',
        'Palkokasvit': '🫛 Palkokasvit',
        'Salaatti': '🥬 Salaatti',
        'Tomaatti': '🍅 Tomaatti',
        'Vihannekset': '🥦 Vihannekset',
        'Yrtit': '🌿 Yrtit',
    }

    for ps in PlantSpecies.objects.all():
        old_cat = ps.kategoria
        new_name = category_map.get(old_cat, f"🌱 {old_cat}")
        
        category_obj, created = Category.objects.get_or_create(name=new_name)
        
        ps.category_link = category_obj
        ps.save()


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_category_plantspecies_category_link'),
    ]

    operations = [
        migrations.RunPython(migrate_categories),
    ]
