# Generated by Django 6.0.2 on 2026-02-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_auto_20260228_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantspecies',
            name='kategoria',
        ),
        migrations.RenameField(
            model_name='plantspecies',
            old_name='category_link',
            new_name='kategoria',
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lajit', to='garden.category', verbose_name='Kategoria'),
        ),
    ]
